spring:
  redis:
    host: 182.254.133.18
    password: XUAN.199951
    timeout: 25s
    port: 6379
  datasource:
    username: root
    password: 199951
    url: jdbc:mysql://182.254.133.18:3306/dtrun?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 25000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  druid:
    username: xiaoxiaoxuan
    password: 199951
  servlet:
    multipart:
      max-file-size: 10MB
server:
  port: 8080
  max-http-header-size: 10MB
  servlet:
    context-path: /api

mybatis:
  config-location: classpath:mybatis/mybatisConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

user:
  iconUrl: https://cdn.jsdelivr.net/gh/WendyBoys/oss/img/icon.png
  userName: 无名氏
  #本地开发时用 http://127.0.0.1:8080/api/icon/
  iconUrlPrefix: http://127.0.0.1:8080/api/icon/
  #iconUrlPrefix: https://dtrun.cn/api/icon/